name: SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v1
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: SonarCloud Scan
        #       set environment variables:
        env:
          GITHUB_TOKEN: ${{ secrets.MVP6_CONVEYOR }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD }}
        #       run sonar maven plugin:
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=Jimbanan_Conveyor -Dsonar.organization=jimbanan -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.coverage.jacoco.xmlReportPaths=./target/site/jacoco/jacoco.xml