name: SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2

      - name: Analyze with SonarCloud
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
        env:
          GITHUB_TOKEN: ${{ secrets.MVP6_CONVEYOR }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        #       run sonar maven plugin:
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=Jimbanan_Conveyor -Dsonar.organization=jimbanan -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.coverage.jacoco.xmlReportPaths=./target/site/jacoco/jacoco.xml